# fly.toml app configuration file generated for art-on-pressies on 2026-04-13T16:41:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'art-on-pressies'
primary_region = 'lhr'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[[mounts]]
  source = 'art_on_pressies_data'
  destination = '/app/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
