# Generated by Django 5.1.15 on 2026-04-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NailShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NailSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_mm', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['width_mm'],
            },
        ),
        migrations.AddField(
            model_name='naildesign',
            name='available_shapes',
            field=models.ManyToManyField(blank=True, related_name='designs', to='core.nailshape'),
        ),
        migrations.CreateModel(
            name='NailSizeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index_sets', to='core.nailsize')),
                ('middle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='middle_sets', to='core.nailsize')),
                ('pinky', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pinky_sets', to='core.nailsize')),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ring_sets', to='core.nailsize')),
                ('thumb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thumb_sets', to='core.nailsize')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='naildesign',
            name='available_size_sets',
            field=models.ManyToManyField(blank=True, related_name='designs', to='core.nailsizeset'),
        ),
    ]
