# Generated by Django 5.1.15 on 2026-04-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nailshape_nailsize_naildesign_available_shapes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nailsizeset',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='nailsizeset',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
