# Generated by Django 5.1.15 on 2026-04-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_nailsizeset_options_nailsizeset_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='naildesign',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
